"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "src/main/resources/assets/inventorysorter/lang"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files":
  - source: /en_us.json
    translation: /%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        en-US: en_us
        ar: ar_ar
        br-FR: br_fr
        zh-CN: zh_cn
        zh-HK: zh_hk
        da: da_dk
        fi: fi_fi
        fr: fr_fr
        de: de_de
        el: el_gr
        it: it_it
        ja: ja_jp
        no: no_no
        pt-BR: pt_br
        ru: ru_ru
        es-ES: es_es
        sv-SE: sv_se
        uk: uk_ua
