"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "src/main/resources/assets/inventorysorter"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files":
  - source: /lang/en_US.json
    translation: /lang/%locale_with_underscore%.json
