name: build
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

env:
  TYPE: ${{ endsWith(github.ref_name, 'main') && 'release' || (endsWith(github.ref_name, 'beta') && 'beta' || 'dev') }}
  NPM_CONFIG_CACHE: /cache/npm

concurrency:
  group:  ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ !endsWith(github.ref_name, 'main') && !endsWith(github.ref_name, 'beta') }}

jobs:
  build:
    name: build
    runs-on: meza-ubuntu-slim
    env:
      HAS_SECRETS: ${{ secrets.DISCORD_WEBHOOK != '' }}
    steps:
      - name: "⬇️ Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Detect documentation changes
        uses: dorny/paths-filter@v4
        id: changes
        with:
          base: ${{ github.event_name == 'push' && github.ref || '' }}
          ref: ${{ github.sha }}
          filters: |
            docs:
              - 'docs/**'
            mod:
              - 'gradle/**'
              - 'scripts/**'
              - 'src/**'
              - 'versions/**'
              - '**/*.kts'
              - '**/*.properties'
              - 'gradlew'
              - 'gradlew.bat'
              - '.releaserc.json'

      - name: "☕ Setup Jdk"
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        if: steps.changes.outputs.mod == 'true'
        with:
          cache: 'gradle'
          cache-dependency-path: |
            versions/*.properties
            *.properties
            *.gradle.kts
          java-version: |
            17
            21
            25
          check-latest: true
          distribution: 'temurin'
          cache-path: /cache/Minecraft/InventorySorter

      - name: "Patch completed languages"
        if: env.HAS_SECRETS == 'true' && steps.changes.outputs.mod == 'true'
        run: ./scripts/patch-completed-langs.sh
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: "🛂 Setup Gradle"
        if: steps.changes.outputs.mod == 'true'
        uses: gradle/actions/setup-gradle@v6
        with:
          validate-wrappers: true
          cache-provider: basic

      - name: "🔓 Adjust the release permissions"
        if: steps.changes.outputs.mod == 'true'
        run: chmod a+x ./scripts/release.sh && chmod +x ./gradlew

      - name: Use Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 25

      - name: "🧵 Install semantic release"
        if: steps.changes.outputs.mod == 'true'
        run: npm i --location=global @meza/mezas-conventional-changelog semantic-release semantic-release-discord-notifier conventional-changelog-conventionalcommits @semantic-release/github @semantic-release/changelog @semantic-release/exec semantic-release-export-data semantic-release-discord

      - name: "🔢 Determine version"
        if: steps.changes.outputs.mod == 'true'
        run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GH_TOKEN: ${{ github.token }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: "ℹ️ Needs Release?"
        if: steps.changes.outputs.mod == 'true'
        run: echo "Needs release published? ${{ steps.get-next-version.outputs.new-release-published == 'true' }}"

      - name: "🔨 Data Gen"
        if: steps.changes.outputs.mod == 'true'
        run: |
          chmod +x ./scripts/datagen.sh
          ./scripts/datagen.sh

      - name: "🏗️ Build & Release to GitHub"
        if: ${{ steps.get-next-version.outputs.new-release-published == 'true' && env.HAS_SECRETS == 'true' && steps.changes.outputs.mod == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
          DO_PUBLISH: steps.get-next-version.outputs.new-release-published
          MODRINTH_ID: ${{ vars.MODRINTH_ID }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_ID: ${{ vars.CURSEFORGE_ID }}
          CURSEFORGE_SLUG: ${{ vars.CURSEFORGE_SLUG }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: npx semantic-release

      - name: "🧪 Run Dev Build"
        if: ${{ steps.get-next-version.outputs.new-release-published != 'true' && steps.changes.outputs.mod == 'true' }}
        run: ./gradlew chiseledGameTest chiseledBuildAndCollect --stacktrace

      - name: "🕵️‍♂️ Collect jars"
        if: steps.changes.outputs.mod == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            build/reports/**/*

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        if: steps.changes.outputs.docs == 'true'
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Use Node.js 25
        if: steps.changes.outputs.docs == 'true'
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 25

      - name: "📚 Build documentation"
        if: steps.changes.outputs.docs == 'true'
        working-directory: ./docs
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        run: |
          pnpm install --frozen-lockfile && \
          pnpm run build
